JobOffer/Controllers/AdminController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JobOffer.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using static JobOffer.Enums.ApplicationEnums;
using AspNetCoreHero.ToastNotification.Abstractions;
using JobOffer.GeneralComponent;

namespace JobOffer.Controllers
{
    public class AdminController : Controller 
    {
        #region Objects
        private readonly ModelContext _context;
        private readonly IWebHostEnvironment _webHostEnviroment;
        private readonly INotyfService _notyf;
        List<string> status = new List<string> { "Pending", "Accept", "Reject" };
        List<string> JobType = new List<string> { "Part Time", "Full Time" };
        #endregion

        #region Constructor
        public AdminController(ModelContext context, IWebHostEnvironment webHostEnviroment, INotyfService notyf)
        {
            _context = context;
            _webHostEnviroment = webHostEnviroment;
            _notyf = notyf;

        }
        #endregion

        #region Methods

        #region Dashboard
        public IActionResult Dashboard()
        {
            try
            {
                #region Get The Numbers Of (Job Posted, Candidates, Companies)
                ViewBag.NumberOfJobPosted = _context.Jobhs.Count(x => x.Status == Status.Accept.ToString());
                ViewBag.NumberOfJobNotPosted = _context.Jobhs.Count(x => x.Status == Status.Pending.ToString() || x.Status == Status.Reject.ToString());
                ViewBag.NumberOfPeople = _context.Useraccounths.Count(x => x.Roleid == 2);
                ViewBag.NumberOfCompanies = _context.Useraccounths.Count();
                #endregion
                ViewBag.AdminUser = HttpContext.Session.GetString("AdminUser");
                string AdminName = ViewBag.AdminUser;
                ViewBag.PImage = HttpContext.Session.GetString("imagePath");

                return View("~/Views/Admin/Dashboard/Dashboard.cshtml");
            }
            catch (Exception ex)
            {
                _notyf.Error("Something Went Wrong!");
                _notyf.Information("ErrMsg: " + ex.Message + "\n\n" +
                                   "StacKTrace: " + ex.StackTrace, 6);
                return View("~/Views/Admin/Dashboard/Dashboard.cshtml");
            }
        }
        #endregion

        #region Manage Users

        #region Get Data Users
        public async Task<IActionResult> MainUser()
        {
            try
            {
                ViewBag.PImage = HttpContext.Session.GetString("imagePath");
                var modelContext = _context.Useraccounths.Include(u => u.Role);
                return View("~/Views/Admin/ManageUsers/MainUser.cshtml", modelContext);
            }
            catch (Exception ex)
            {
                _notyf.Error("Something Went Wrong!");
                _notyf.Information("ErrMsg: " + ex.Message + "\n\n" +
                                   "StacKTrace: " + ex.StackTrace, 6);
                return View("~/Views/Admin/ManageUsers/MainUser.cshtml");
            }
        }
        #endregion

        #region Get Data Users Details
        public async Task<IActionResult> DetailsUser(decimal? id)
        {
            try
            {
                ViewBag.PImage = HttpContext.Session.GetString("imagePath");

                if (id == null)
                {
                    return NotFound();
                }

                var useraccounth = await _context.Useraccounths
                    .Include(u => u.Role)
                    .FirstOrDefaultAsync(m => m.Userid == id);
                if (useraccounth == null)
                {
                    return NotFound();
                }

                return View("~/Views/Admin/ManageUsers/DetailsUser.cshtml", useraccounth);
            }
            catch (Exception ex)
            {
                _notyf.Error("Something Went Wrong!");
                _notyf.Information("ErrMsg: " + ex.Message + "\n\n" +
                                   "StacKTrace: " + ex.StackTrace, 6);
                return View("~/Views/Admin/ManageUsers/DetailsUser.cshtml");
            }
        }
        #endregion

        #region Create User

        #region Get 
        public IActionResult CreateUser()
        {
            ViewBag.PImage = HttpContext.Session.GetString("imagePath");

            ViewData["Roleid"] = new SelectList(_context.Rolehs, "Roleid", "Rolename");
            return View("~/Views/Admin/ManageUsers/CreateUser.cshtml");
        }
        #endregion

        #region Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateUser([Bind("Userid,Fullname,Username,Email,Phonenumber,Industialname,Roleid,Password,Imagepath, ImageFile")] Useraccounth useraccounth)
        {
            try
            {
                ViewBag.PImage = HttpContext.Session.GetString("imagePath");

                if (ModelState.IsValid)
                {
                    useraccounth.Imagepath = useraccounth.ImageFile != null ?
                               new Localization().SaveImage(_webHostEnviroment, useraccounth.ImageFile.FileName, "PersonalImages", useraccounth.ImageFile) :
                               string.Empty;
                    
                    _context.Add(useraccounth);
                    if(_context.SaveChangesAsync().IsCompletedSuccessfully)
                    {
                         _notyf.Success("Successfully Added");
                    } 
                    
                    return RedirectToAction(nameof(MainUser));
                }
                ViewData["Roleid"] = new SelectList(_context.Rolehs, "Roleid", "Rolename", useraccounth.Roleid);
                return View("~/Views/Admin/ManageUsers/CreateUser.cshtml", useraccounth);
            }
            catch (Exception ex)
            {
                _notyf.Error("Something Went Wrong!");
                _notyf.Information("ErrMsg: " + ex.Message + "\n\n" +
                                   "StacKTrace: " + ex.StackTrace, 6);
                return View("~/Views/Admin/ManageUsers/CreateUser.cshtml");
            }
        }
        #endregion

        #endregion

        #region Edit User

        #region Get
        public async Task<IActionResult> EditUser(decimal? id)
        {
            ViewBag.PImage = HttpContext.Session.GetString("imagePath");

            if (id == null)
            {
                return NotFound();
            }

            var useraccounth = await _context.Useraccounths.FindAsync(id);
            if (useraccounth == null)
            {
                return NotFound();
            }
            ViewData["Roleid"] = new SelectList(_context.Rolehs, "Roleid", "Rolename", useraccounth.Roleid);
            return View("~/Views/Admin/ManageUsers/EditUser.cshtml", useraccounth);
        }
        #endregion

        #region Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUser(decimal id, [Bind("Userid,Fullname,Username,Email,Phonenumber,Industialname,Roleid,Password,Imagepath, ImageFile")] Useraccounth useraccounth)
        {
            ViewBag.PImage = HttpContext.Session.GetString("imagePath");

            if (id != useraccounth.Userid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (useraccounth.ImageFile != null)
                    {
                        useraccounth.Imagepath = useraccounth.ImageFile != null ?
                               new Localization().SaveImage(_webHostEnviroment, useraccounth.ImageFile.FileName, "PersonalImages", useraccounth.ImageFile) :
                               string.Empty;
  
                    }
                    else
                    {
                        useraccounth.Imagepath = _context.Useraccounths.Where(x => x.Userid == id).AsNoTracking<Useraccounth>().FirstOrDefault().Imagepath;

                    }

                    _context.Update(useraccounth);
                    await _context.SaveChangesAsync();
                    _notyf.Success("Successfully Updated!");


                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UseraccounthExists(useraccounth.Userid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(MainUser));
            }
            ViewData["Roleid"] = new SelectList(_context.Rolehs, "Roleid", "Rolename", useraccounth.Roleid);
            return View("~/Views/Admin/ManageUsers/EditUser.cshtml", useraccounth);
        }
        #endregion

        #endregion

        #region Delete User

        #region Get
        public async Task<IActionResult> DeleteUser(decimal? id)
        {
            ViewBag.PImage = HttpContext.Session.GetString("imagePath");

            if (id == null)
            {
                return NotFound();
            }

            var useraccounth = await _context.Useraccounths
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.Userid == id);
            if (useraccounth == null)
            {
                return NotFound();
            }

            return View("~/Views/Admin/ManageUsers/DeleteUser.cshtml", useraccounth);
        }
        #endregion

        #region Post
        [HttpPost, ActionName("DeleteUser")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUser(decimal id)
        {
            try
            {

JobOffer/Views/Admin/ManageTestmonial/CreateTestmonial.cshtml
@model JobOffer.Models.Testmonialh

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_DashboardAdminLayout.cshtml";
}



<div class="page-header" style="margin-left:250px;margin-top:30px">
<div class="page-block">
    <div class="row align-items-center">
        <div class="col-md-12">
            <div class="page-header-title">
                    <h5 class="m-b-10" style="font-size:20px;font-weight:bold; color:#89ba16">Create  Testmonial</h5>
            </div>
            <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-action="Dashboard" asp-controller="Admin"><i class="feather icon-home"></i></a></li>
                    <li class="breadcrumb-item"><a href="#!">Manage  Testmonials</a></li>
                <li class="breadcrumb-item"><a href="#!">Create New</a></li>
            </ul>
        </div>
    </div>
</div>
</div>




<div style="margin-left:700px">
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateTestmonial">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" asp-items="ViewBag.Status" class="form-control" ></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Userid" class="control-label"></label>
                <select asp-for="Userid" class ="form-control" asp-items="ViewBag.Userid"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" /> |

                    <a asp-action="MainTestmonials">Back to List</a>

            </div>
        </form>
    </div>
</div>


</div>
@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
*@
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<h1>h</h1>

JobOffer/Views/Admin/ManageTestmonial/DeleteTestmonial.cshtml
@model JobOffer.Models.Testmonialh

@{
    ViewData["Title"] = "Delete";
     Layout = "~/Views/Shared/_DashboardAdminLayout.cshtml";
}
<div class="page-header" style="margin-left:250px;margin-top:30px">
<div class="page-block">
    <div class="row align-items-center">
        <div class="col-md-12">
            <div class="page-header-title">
                    <h5 class="m-b-10" style="font-size:20px;font-weight:bold; color:#89ba16">Delete  Testmonial</h5>
            </div>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a asp-action="Dashboard" asp-controller="Admin"><i class="feather icon-home"></i></a></li>
                    <li class="breadcrumb-item"><a href="#!">Manage  Testmonials</a></li>
                <li class="breadcrumb-item"><a href="#!">Delete</a></li>
            </ul>
        </div>
    </div>
</div>
</div>

<div style="margin-left:250px">
      <h3 style="color:crimson">-Are you sure you want to delete this Testmonial?</h3>
      <br />
<div>
  
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Email)
        </dd class>
    </dl>
    <br />
    <br />
    <form asp-action="DeleteTestmonial" method="post">
        <input type="hidden" asp-for="Testmonialid" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="MainTestmonials">Back to List</a>
    </form>
</div>
</div>
<br />
<br />

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h1>h</h1>

JobOffer/Views/Admin/ManageTestmonial/DetailsTestmonial.cshtml
@model JobOffer.Models.Testmonialh

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_DashboardAdminLayout.cshtml";
}

<div class="page-header" style="margin-left:250px;margin-top:30px">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">
                    <h5 class="m-b-10" style="font-size:20px;font-weight:bold; color:#89ba16">Details  Testmonial</h5>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-action="Dashboard" asp-controller="Admin"><i class="feather icon-home"></i></a></li>
                    <li class="breadcrumb-item"><a href="#!">Manage  Testmonials</a></li>
                    <li class="breadcrumb-item"><a href="#!">Details</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>


<div style="margin-left:250px">
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Email)
        </dd>
    </dl>

    <br />
    <a asp-action="EditTestmonial" asp-route-id="@Model.Testmonialid">Edit</a> |
    <a asp-action="MainTestmonials">Back to List</a>
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<h1>h</h1>

JobOffer/Views/Admin/ManageTestmonial/EditTestmonial.cshtml
@model JobOffer.Models.Testmonialh

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_DashboardAdminLayout.cshtml";
}

<div class="page-header" style="margin-left:250px;margin-top:30px">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">
                    <h5 class="m-b-10" style="font-size:20px;font-weight:bold; color:#89ba16">Edit  Testmonial</h5>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-action="Dashboard" asp-controller="Admin"><i class="feather icon-home"></i></a></li>
                    <li class="breadcrumb-item"><a href="#!">Manage  Testmonials</a></li>
                    <li class="breadcrumb-item"><a href="#!">Edit</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>


<div style="margin-left:250px">
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditTestmonial">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Testmonialid" />
            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control" asp-items="ViewBag.Status"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Userid" class="control-label"></label>
                <select asp-for="Userid" class="form-control" asp-items="ViewBag.Userid"></select>
                <span asp-validation-for="Userid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" /> |

                    <a asp-action="MainTestmonials">Back to List</a>
            </div>
        </form>
    </div>
</div>


</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
*@
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<h1>h</h1>

JobOffer/Views/Admin/ManageTestmonial/MainTestmonials.cshtml
@model IEnumerable<JobOffer.Models.Testmonialh>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_DashboardAdminLayout.cshtml";
}

<div class="page-header" style="margin-left:250px;margin-top:30px">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">
                    <h5 class="m-b-10" style="font-size:20px;font-weight:bold; color:#89ba16">Manage Testmonials</h5>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-action="Dashboard" asp-controller="Admin"><i class="feather icon-home"></i></a></li>
                    <li class="breadcrumb-item"><a href="#!">Manage  Testmonials</a></li>            
                </ul>
            
            </div>
        </div>
    </div>
</div>
<a asp-action="CreateTestmonial">

    <button type="button"
            class="btn btn-outline-success" style="margin-left:250px">
        Create New
    </button>
</a>
<div style="width:350px;">
    <table class ="table is-bordered" style="margin-top:20px;margin-left:250px">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Message)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Message)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Username)
            </td>
            <td>
                    <a asp-action="EditTestmonial" asp-route-id="@item.Testmonialid">Edit</a> |
                    <a asp-action="DetailsTestmonial" asp-route-id="@item.Testmonialid">Details</a> |
                    <a asp-action="DeleteTestmonial" asp-route-id="@item.Testmonialid">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>

    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

    <h1>h</h1>

JobOffer/Views/Admin/ManageTestmonial/ManagePendingTestmonial.cshtml
@model IEnumerable<JobOffer.Models.Testmonialh>

@{
    Layout = "~/Views/Shared/_DashboardAdminLayout.cshtml";
}

<div class="page-header" style="margin-left:250px;margin-top:30px">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">
                    <h5 class="m-b-10" style="font-size:20px;font-weight:bold; color:#89ba16">Pending Testmonial</h5>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-action="Dashboard" asp-controller="Admin"><i class="feather icon-home"></i></a></li>
                    <li class="breadcrumb-item"><a href="#!">Manage Testmonial</a></li>
                    <li class="breadcrumb-item"><a href="#!">Pending Testmonial</a></li>

                </ul>
            </div>
        </div>
    </div>
</div>

<div style="width:350px">
    <table class="table is-bordered" style="margin-top:50px;margin-left:250px">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Message)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.User)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Message)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.User.Username)
                    </td>
                    <td>
                        <a asp-action="AcceptTestmonial" asp-route-id="@item.Testmonialid">Accept</a> |
                        <a asp-action="RejectTestmonial" asp-route-id="@item.Testmonialid">Reject</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<h1>h</h1>

JobOffer/Views/Admin/ManageTestmonial/ManageRejectingTestmonial.cshtml
@model IEnumerable<JobOffer.Models.Testmonialh>

@{
    Layout = "~/Views/Shared/_DashboardAdminLayout.cshtml";
}

<div class="page-header" style="margin-left:250px;margin-top:30px">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">
                    <h5 class="m-b-10" style="font-size:20px;font-weight:bold; color:#89ba16">Manage Rejecting</h5>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-action="Dashboard" asp-controller="Admin"><i class="feather icon-home"></i></a></li>
                    <li class="breadcrumb-item"><a href="#!">Manage Testmonial</a></li>
                    <li class="breadcrumb-item"><a href="#!">Manage Rejecting</a></li>

                </ul>
            </div>
        </div>
    </div>
</div>

<div style="width:500px">
    <table class="table is-bordered" style="margin-top:50px;margin-left:250px">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Message)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.User)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Message)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.User.Username)
                    </td>
                    <td>
                        <a asp-action="AcceptTestmonial" asp-route-id="@item.Testmonialid">Accept</a> |
                        <a asp-action="MainTestmonials" asp-route-id="@item.Testmonialid">Cancel</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h1>h</h1>