JobOffer/Controllers/GuestUserController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using JobOffer.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using static JobOffer.Enums.ApplicationEnums;


namespace JobOffer.Controllers
{
    public class GuestUserController : Controller
    {
        #region Object 
        private readonly INotyfService _notyf;
        private readonly ModelContext _context;
        #endregion

        #region Constructors
        public GuestUserController(ModelContext context, INotyfService notyf)
        {
            _context = context;
            _notyf = notyf;
        }
        #endregion

        #region Methods

        #region Home
        public IActionResult Home()
        {
            try
            {
                #region List Of (Job, Address, UserAccount)
                var JobList = _context.Jobhs.Where(x => x.Status == Status.Accept.ToString()).ToList();
                var AddressList = _context.Addresshes.ToList();
                var AccountsList = _context.Useraccounths.ToList();
                #endregion

                #region Get The Numbers Of (Job Posted, Candidates, Companies)
                ViewBag.NumberOfJobPosted = JobList.Count(x => x.Status == Status.Accept.ToString());
                ViewBag.NumberOfPeople = AccountsList.Count(x => x.Roleid == 2);
                ViewBag.NumberOfCompanies = AccountsList.Count();
                #endregion

                #region Join Tables Between(Job, Address, UserAccount)
                var modelView = from addr in AddressList
                                join job in JobList on addr.Addressid equals job.Addressid
                                join Acc in AccountsList on job.Userid equals Acc.Userid
                                select new JobViewJoin { Job = job, Address = addr, Account = Acc };
                #endregion


                return View(modelView);
            }
            catch (Exception ex)
            {
                _notyf.Warning(ex.Message);
                return View();
            }
        }
        #endregion

        #region About
        public IActionResult About()
        {
            return View();
        }
        #endregion

        #region Contact
        public IActionResult Contact()
        {
            return View();
        }
        #endregion

        #region Services
        public IActionResult Services()
        {
            return View();
        }
        #endregion
        
        #region Testmonial
        public IActionResult Testmonial()
        {
            #region Join Tables Between(Testmonial, UserAccount)
            var modelView = from user in _context.Useraccounths.ToList()
                            join test in _context.Testmonialhs.Where(x => x.Status == Status.Accept.ToString()).ToList() on user.Userid equals test.Userid
                            where test.Status == Status.Accept.ToString()
                            select new TestmonialViewJoin { Test = test, Account = user };
            #endregion

            return View(modelView);
        }
        #endregion

        #region Search

        public IActionResult Search(string job)
        {
            #region List Of (Job, Address, UserAccount)
            var JobList = _context.Jobhs.Where(x => x.Status == Status.Accept.ToString()).ToList();
            var AddressList = _context.Addresshes.ToList();
            var AccountsList = _context.Useraccounths.ToList();
            #endregion

            #region Join Tables Between(Job, Address, UserAccount)
            var modelView = from addr in AddressList
                            join jobb in JobList on addr.Addressid equals jobb.Addressid
                            join Acc in AccountsList on jobb.Userid equals Acc.Userid
                            select new JobViewJoin { Job = jobb, Address = addr, Account = Acc };
            #endregion

            #region Search Process
            if (job == null)
            {
                return View(nameof(Home), modelView);
            }
            else
            {

                var result = modelView.Where(x => x.Job.Jobname.ToLower().Contains(job.ToLower()) || x.Job.Jobname.ToLower().StartsWith(job.ToLower())).ToList();
                return View(nameof(Home), result);
            }
            #endregion

        }

        #endregion

        #endregion

    }
}

JobOffer/Controllers/JobsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using JobOffer.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using static JobOffer.Enums.ApplicationEnums;
using AspNetCoreHero.ToastNotification.Abstractions;
using JobOffer.GeneralComponent;

namespace JobOffer.Controllers
{
    public class JobsController : Controller
    {
        #region Objects
        private readonly INotyfService _notyf;
        private readonly ModelContext _context;
        private readonly IWebHostEnvironment _webHostEnviroment;
        #endregion

        #region Constructors
        public JobsController(ModelContext context, IWebHostEnvironment webHostEnviroment, INotyfService notyf)
        {
            _context = context;
            _webHostEnviroment = webHostEnviroment;
            _notyf = notyf;
        }
        #endregion

        #region Methods

        #region Post a Job

        #region Get
        public IActionResult postJob()
        {
            #region Values Of Drop Down List(AddressName, AddressCity, CatygoryJob)
            ViewData["AddressName"] = new SelectList(_context.Addresshes, "Addressid", "Addressname");
            ViewData["AddressCity"] = new SelectList(_context.Addresshes, "Addressid", "Addresscity");
            ViewData["Jobcategoryid"] = new SelectList(_context.Jobcategoryhs, "Jobcategoryid", "Jobcategoryname"); 
            #endregion

            return View();
        }
        #endregion

        #region Post
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult postJob([Bind("Jobname, Jobdescription, Jobtype, Jobsalary, Addressid, Jobcategoryid, Jobimage, ImageFile")] Jobh job)
        {

            try
            {
                #region 'Set The User Id:The Current User' and 'set Status:Pending'
                job.Userid = (decimal)HttpContext.Session.GetInt32("UserId");
                job.Status = "Pending";
                #endregion
                
                job.Jobimage = job.ImageFile != null ?
                               new Localization().SaveImage(_webHostEnviroment, job.ImageFile.FileName, "JobsImages", job.ImageFile) :
                               string.Empty;
                
                    
                _context.Add(job);
                _context.SaveChanges();
                _notyf.Success("Successfully Posted");
                _notyf.Information("Under process By Admin, You Will Receive an email from Admin when accept", 6);

                #region Objects
                var UserId = HttpContext.Session.GetInt32("UserId");
                var UserInfo = _context.Useraccounths.Where(x => x.Userid == UserId).FirstOrDefault();
                var JobInfo = _context.Jobhs.Where(x => x.Jobid == job.Jobid).FirstOrDefault();
                var EmailInfo = _context.Useraccounths.Where(x => x.Userid == JobInfo.Userid).FirstOrDefault();
                var AdminInfo = _context.Useraccounths.Where(x => x.Roleid == 1).FirstOrDefault();
                Applyjob applyjob = new Applyjob();
                #endregion

                #region Sending Email To Admin
                string subject = "Post a Job For " + JobInfo.Jobname + " " + UserInfo.Fullname;
                string body = "The User " + " " + UserInfo.Fullname + " "
                                             + "Post For The Job "
                                             + JobInfo.Jobname
                                             + " at "
                                             + DateTime.Now.ToLongDateString()
                                             + " Check The Page For Your Manage Jobs";

                new Localization().sendEmail(AdminInfo.Email, subject, body);
                #endregion

                #region Sending Email To User

                subject = "Post a Job For " + JobInfo.Jobname;
                body = "Ms / Mrs" + " " + UserInfo.Fullname + " "
                                            + "Thank You For Posting The Job "
                                            + JobInfo.Jobname
                                            + " The Admin Will Response To You As Possible as :) \n"
                                            + "Note: See Your Page 'My Post Job' If The Admin Accepted";

                new Localization().sendEmail(UserInfo.Email, subject, body);
                #endregion

                #region Values Of Drop Down List(AddressName, AddressCity, CatygoryJob)
                ViewData["AddressName"] = new SelectList(_context.Addresshes, "Addressid", "Addressname", job.Addressid);
                ViewData["AddressCity"] = new SelectList(_context.Addresshes, "Addressid", "Addresscity", job.Addressid);
                ViewData["Jobcategoryid"] = new SelectList(_context.Jobcategoryhs, "Jobcategoryid", "Jobcategoryname", job.Jobcategory);
                #endregion

                return View();
            }
            catch (Exception ex)
            {
                _notyf.Error("Something Went Wrong ...");
                _notyf.Information("Error Msg :" + ex.Message + "\n" +
                                   "StackTrace : " + ex.StackTrace);
                return View();
            }
        }
        #endregion

        #endregion
        
        #region My Post Jobs

        public IActionResult MyPostJob()
        {
            #region List Of (Job, Address, UserAccount)
            var JobList = _context.Jobhs.Where(x => x.Status == Status.Accept.ToString()).ToList();
            var AddressList = _context.Addresshes.ToList();
            var AccountsList = _context.Useraccounths.ToList();
            #endregion

            #region Join Tables Between(Job, Address)
            var modelView = from addr in AddressList
                            join job in JobList on addr.Addressid equals job.Addressid
                            join Acc in AccountsList on job.Userid equals Acc.Userid
                            where job.Userid == HttpContext.Session.GetInt32("UserId")
                            select new JobViewJoin { Job = job, Address = addr, Account = Acc };

            #endregion

            return View(modelView);
        }

        #endregion

        #region Apply a Job        
        public IActionResult ApplyJob(decimal? Jobid)
        {
            ViewBag.Jobid = Jobid;

            #region List Of (Job, Address, UserAccount)
            var JobList = _context.Jobhs.Where(x => x.Status == Status.Accept.ToString()).ToList();
            var AddressList = _context.Addresshes.ToList();
            var AccountsList = _context.Useraccounths.ToList();
            #endregion

            #region Join Tables Between(Job, Address)
            var modelView = from addr in AddressList
                            join job in JobList on addr.Addressid equals job.Addressid
                            join Acc in AccountsList on job.Userid equals Acc.Userid
                            where job.Jobid == Jobid
                            select new JobViewJoin { Job = job, Address = addr, Account = Acc };
            #endregion

            return View(modelView);
        }

        #endregion
            
        #region Apply a Job With Submission
        public IActionResult ApplyJobSubmission( decimal JobId, [Bind("Attchpath, PdfFile")] Attchmenth attchment)
        {
            #region Objects
            var UserId = HttpContext.Session.GetInt32("UserId");
            var UserInfo = _context.Useraccounths.Where(x => x.Userid == UserId).FirstOrDefault();
            var JobInfo = _context.Jobhs.Where(x => x.Jobid == JobId).FirstOrDefault();
            var EmailInfo = _context.Useraccounths.Where(x => x.Userid == JobInfo.Userid).FirstOrDefault();
            Applyjob applyjob = new Applyjob(); 
            #endregion

            #region Make a File
            string wwwrootPath = _webHostEnviroment.WebRootPath;
            string fileName = Guid.NewGuid().ToString() + "_" + attchment.PdfFile.FileName;
            string extension = Path.GetExtension(attchment.PdfFile.FileName);

            string path = Path.Combine(wwwrootPath + "/CvFiles/" + JobInfo.Jobcategory + "/" + JobInfo.Jobid +"_" + fileName);
            using (var filestream = new FileStream(path, FileMode.Create))
            {
                attchment.PdfFile.CopyToAsync(filestream);
            }
            #endregion

            #region Fill Data Attachment
            attchment.Attchpath = fileName;
            attchment.Userid = UserId;
            _context.Add(attchment);
            _context.SaveChanges(); 
            #endregion

            #region Fill Data Apply
            applyjob.Attachid = _context.Attchmenths.Where(x => x.Userid == UserId).Select(x => x.Attachid).FirstOrDefault();
            applyjob.Userid = UserId;
            applyjob.Jobid = JobId; 
            _context.Add(applyjob);
            _context.SaveChanges();
            #endregion

            #region Sending Email To Admin

            string subjectAdmin = "Applied Job For "  + JobInfo.Jobname + " " + UserInfo.Fullname;
            string bodyAdmin = "The User " + " " + UserInfo.Fullname + " "
                                         + "Applied For The Job"
                                         + JobInfo.Jobname
                                         + " at "
                                         + DateTime.Now.ToLongDateString();

            new Localization().sendEmail(EmailInfo.Email, subjectAdmin, bodyAdmin);

         
              
            #endregion

            #region Sending Email To User
         
            string subject = "Apply Job For " + JobInfo.Jobname;
            string body = "Ms / Mrs" + " " + UserInfo.Fullname + " "
                                                               + "Thank You For Applying The Job "

JobOffer/Views/Shared/_ActualUserLayout.cshtml
@{
    var userName = ViewBag.userName;
}
<!DOCTYPE html>

<html>
   
<head>
    
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Assests/css/custom-bs.css">
    <link rel="stylesheet" href="~/Assests/css/jquery.fancybox.min.css">
    <link rel="stylesheet" href="~/Assests/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/Assests/fonts/icomoon/style.css">
    <link rel="stylesheet" href="~/Assests/fonts/line-icons/style.css">
    <link rel="stylesheet" href="~/Assests/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Assests/css/animate.min.css">
 

    <link rel="stylesheet" href="~/Assests/css/style.css">
</head>
<body>
    <!-- NAVBAR -->
    <header class="site-navbar mt-3">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="site-logo col-6"><a asp-action="Home" asp-controller="ActualUser">JobBoard</a></div>

                <nav class="mx-auto site-navigation">
                    <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
                        <li><a asp-action="Home" asp-controller="ActualUser" class="nav-link active">Home</a></li>
                        <li><a asp-action="About" asp-controller="ActualUser">About</a></li>
                        <li><a asp-action="Testmonial" asp-controller="ActualUser">Testmonial</a></li>
                        <li><a asp-action="Services" asp-controller="ActualUser">Services</a></li>
                        <li><a asp-action="Contact" asp-controller="ActualUser">Contact</a></li>
                        <li class="has-children">
                            <h3 style="color:aliceblue;font-size:18px;">My Profile</h3>
                            <ul class="dropdown">
                                <li>
                                    <a asp-action="MyProfile" asp-controller="ActualUser">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="25" fill="currentColor" class="bi bi-person-square" viewBox="0 0 16 16" style="color:#89ba16">
                                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                                            <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm12 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1v-1c0-1-1-4-6-4s-6 3-6 4v1a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12z" />
                                        </svg>
                                    
                                    
                                    @userName
                                    
                                    
                                    </a>
                                </li>
                                <li>
                                    
                                    <a asp-action="MyPostJob" asp-controller="Jobs">

                                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="25" fill="currentColor" class="bi bi-bookmark-plus-fill" viewBox="0 0 16 16" style="color:#89ba16">
                                            <path fill-rule="evenodd" d="M2 15.5V2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.74.439L8 13.069l-5.26 2.87A.5.5 0 0 1 2 15.5zm6.5-11a.5.5 0 0 0-1 0V6H6a.5.5 0 0 0 0 1h1.5v1.5a.5.5 0 0 0 1 0V7H10a.5.5 0 0 0 0-1H8.5V4.5z" />
                                        </svg>
                                      My Post Jobs
                                    </a>
                                </li>
                                <li>
                                    <a asp-action="MyAppliedJobs" asp-controller="Jobs">

                                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="25" fill="currentColor" class="bi bi-send-check-fill" viewBox="0 0 16 16" style="color:#89ba16">
                                            <path d="M15.964.686a.5.5 0 0 0-.65-.65L.767 5.855H.766l-.452.18a.5.5 0 0 0-.082.887l.41.26.001.002 4.995 3.178 1.59 2.498C8 14 8 13 8 12.5a4.5 4.5 0 0 1 5.026-4.47L15.964.686Zm-1.833 1.89L6.637 10.07l-.215-.338a.5.5 0 0 0-.154-.154l-.338-.215 7.494-7.494 1.178-.471-.47 1.178Z" />
                                            <path d="M16 12.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0Zm-1.993-1.679a.5.5 0 0 0-.686.172l-1.17 1.95-.547-.547a.5.5 0 0 0-.708.708l.774.773a.75.75 0 0 0 1.174-.144l1.335-2.226a.5.5 0 0 0-.172-.686Z" />
                                        </svg>
                                        My Applied Jobs
                                    </a>
                                </li>


                            </ul>
                        </li>

                        </ul>
                    
                </nav>








                <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
                    <div class="ml-auto">
                        <a asp-action="postJob" asp-controller="Jobs" class="btn btn-outline-white border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-add"></span>Post a Job</a>

                        <a asp-action="logOut" asp-controller="Auth" class="btn btn-primary border-width-2 d-none d-lg-inline-block">
                            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="25" fill="currentColor" class="bi bi-power" viewBox="0 0 16 16" >
                                <path d="M7.5 1v7h1V1h-1z" />
                                <path d="M3 8.812a4.999 4.999 0 0 1 2.578-4.375l-.485-.874A6 6 0 1 0 11 3.616l-.501.865A5 5 0 1 1 3 8.812z" />
                            </svg>
                            Log Out
                        </a>





                 

                    <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span class="icon-menu h3 m-0 p-0 mt-2"></span>
                        
                    </a>
                </div>

            </div>
        </div>

    </header>


    <div>
        @RenderBody()
    </div>


    <footer class="site-footer">

        <a href="#top" class="smoothscroll scroll-top">
            <span class="icon-keyboard_arrow_up"></span>
        </a>

        <div class="container">
            <div class="row mb-5">
                <div class="col-6 col-md-3 mb-4 mb-md-0" style="margin-left:333px">
                    <h3>Company</h3>
                    <ul class="list-unstyled">
                        <li><a asp-action="About" asp-controller="ActualUser">About us</a></li>
                        <li><a asp-action="Testmonial" asp-controller="ActualUser">Testimonial</a></li>
                        <li><a asp-action="Services" asp-controller="ActualUser">Services</a></li>
                        <li><a asp-action="Contact" asp-controller="ActualUser">Contact</a></li>

                    </ul>
                </div>

                <div class="col-6 col-md-3 mb-4 mb-md-0">
                    <h3>Contact Us</h3>
                    <div class="footer-social">
                        <a href="https://www.facebook.com/"><span class="icon-facebook"></span></a>

                        <a href="https://www.instagram.com/"><span class="icon-instagram"></span></a>
                        <a href="https://www.linkedin.com/"><span class="icon-linkedin"></span></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="row text-center">
                <div class="col-12">
                    <p class="copyright">
                        <small>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This Web Site is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="#">Majed Atawneh</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </small>
                    </p>
                </div>
            </div>
        </div>
    </footer>

    <!-- SCRIPTS -->
    <script src="~/Assests/js/jquery.min.js"></script>
    <script src="~/Assests/js/bootstrap.bundle.min.js"></script>
    <script src="~/Assests/js/isotope.pkgd.min.js"></script>
    <script src="~/Assests/js/stickyfill.min.js"></script>
    <script src="~/Assests/js/jquery.fancybox.min.js"></script>
    <script src="~/Assests/js/jquery.easing.1.3.js"></script>

    <script src="~/Assests/js/jquery.waypoints.min.js"></script>
    <script src="~/Assests/js/jquery.animateNumber.min.js"></script>
    <script src="~/Assests/js/owl.carousel.min.js"></script>

    <script src="~/Assests/js/bootstrap-select.min.js"></script>

    <script src="~/Assests/js/custom.js"></script>

    <script>
        function myFunction() {
            var x = document.getElementById("password");
            if (x.type === "password") {
                x.type = "text";
            } else {
                x.type = "password";
            }
        }
    </script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await Component.InvokeAsync("Notyf")
@RenderSection("Scripts", required: false)


</body>
</html>

JobOffer/Views/Shared/_GuestUserLayout.cshtml
<!DOCTYPE html>

<html>
    
<head>
      
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Assests/css/custom-bs.css">
    <link rel="stylesheet" href="~/Assests/css/jquery.fancybox.min.css">
    <link rel="stylesheet" href="~/Assests/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/Assests/fonts/icomoon/style.css">
    <link rel="stylesheet" href="~/Assests/fonts/line-icons/style.css">
    <link rel="stylesheet" href="~/Assests/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Assests/css/animate.min.css">

    <link rel="stylesheet" href="~/Assests/css/style.css">
</head>
<body>
    <!-- NAVBAR -->
    <header class="site-navbar mt-3">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="site-logo col-6" ><a  asp-action="Home" asp-controller="GuestUser" >JobBoard</a></div>

                <nav class="mx-auto site-navigation">
                    <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
                        <li><a asp-action="Home" asp-controller="GuestUser" class="nav-link active">Home</a></li>
                        <li><a asp-action="About" asp-controller="GuestUser">About</a></li>
                        <li><a asp-action="Testmonial" asp-controller="GuestUser">Testmonial</a></li>
                        <li><a asp-action="Services" asp-controller="GuestUser">Services</a></li> 
                        <li><a asp-action="Contact" asp-controller="GuestUser" >Contact</a></li>
                        @*<li class="has-children">
                            <a href="job-listings.html">Job Listings</a>
                            <ul class="dropdown">
                                <li><a href="job-single.html">Job Single</a></li>
                                <li><a href="post-job.html">Post a Job</a></li>
                            </ul>
                        </li>*@
                        
                        
                      @*  <li><a href="blog.html">Blog</a></li>*@
                       
                        <li class="d-lg-none"><a asp-action="Login" asp-controller="Auth"><span class="mr-2">+</span> Post a Job</a></li>
                        <li class="d-lg-none"><a asp-action="Login" asp-controller="Auth">Log In</a></li>
                       



                    </ul>
                </nav>

                <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
                    <div class="ml-auto" >
                        <a asp-action="Login" asp-controller="Auth" class="btn btn-outline-white border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-add"></span>Post a Job</a>
                        <a asp-action="Login" asp-controller="Auth" class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-lock_outline"></span>Log In</a>
                    </div>
                    <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span class="icon-menu h3 m-0 p-0 mt-2"></span></a>
                </div>

            </div>
        </div>
   
    </header>

  
    <div>
        @RenderBody()
    </div>



    <footer class="site-footer">

        <a href="#top" class="smoothscroll scroll-top">
            <span class="icon-keyboard_arrow_up"></span>
        </a>

        <div class="container">
            <div class="row mb-5">
                <div class="col-6 col-md-3 mb-4 mb-md-0" style="margin-left:333px">
                    <h3>Company</h3>
                    <ul class="list-unstyled">
                        <li><a asp-action="About" asp-controller="GuestUser">About us</a></li>
                        <li><a asp-action="Testmonial" asp-controller="GuestUser">Testimonial</a></li>
                        <li><a asp-action="Services" asp-controller="GuestUser">Services</a></li>
                        <li><a asp-action="Contact" asp-controller="GuestUser">Contact</a></li>
                        
                    </ul>
                </div>
             
                <div class="col-6 col-md-3 mb-4 mb-md-0" >
                    <h3>Contact Us</h3>
                    <div class="footer-social">
                        <a href="https://www.facebook.com/"><span class="icon-facebook"></span></a>
                     
                        <a href="https://www.instagram.com/"><span class="icon-instagram"></span></a>
                        <a href="https://www.linkedin.com/"><span class="icon-linkedin"></span></a>
                    </div>
                </div>
            </div>
           </div>
            <div class="row text-center">
                <div class="col-12">
                    <p class="copyright">
                        <small>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This Web Site is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="#" >Majed Atawneh</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </small>
                    </p>
                </div>
            </div>
        
    </footer>

    <!-- SCRIPTS -->
    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.bundle.min.js"></script>
    <script src="js/isotope.pkgd.min.js"></script>
    <script src="js/stickyfill.min.js"></script>
    <script src="js/jquery.fancybox.min.js"></script>
    <script src="js/jquery.easing.1.3.js"></script>

    <script src="js/jquery.waypoints.min.js"></script>
    <script src="js/jquery.animateNumber.min.js"></script>
    <script src="js/owl.carousel.min.js"></script>

    <script src="js/bootstrap-select.min.js"></script>

    <script src="js/custom.js"></script>


    <script>
        function myFunction() {
            var x = document.getElementById("fnames");
            if (x.type === "password") {
                x.type = "text";
            } else {
                x.type = "password";
            }
        }
    </script>
     <script src="~/js/site.js" asp-append-version="true"></script>
        @await Component.InvokeAsync("Notyf")
@RenderSection("Scripts", required: false)

</body>
</html>